server:
  port: 8081

spring:
  application:
    name: sb-kafka-producer

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topicos:
  pagamento:
    request:
      topic: pagamento-topic