server:
  port: 8080

app:
  jwt:
    secret: troque-por-um-segredo-bem-grande-de-pelo-menos-32-caracteres
    expirationMs: 3600000

spring:
  main:
    allow-circular-references: true
  application:
    name: SpringSecurityJWT
  datasource:
    url: jdbc:h2:mem:testdb
    
